import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { HERO_V2_MUSIC_PROMPT } from "../src/hero/build-v2/audio";
import { BEAT_COPY, type CopyKey } from "../src/hero/build-v2/beat-copy";
import { FPS_V2, TOTAL_FRAMES_V2 } from "../src/hero/build-v2/timeline";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, "..");
const outputDir = path.resolve(projectRoot, "public/audio/hero-build-v2");

const API_BASE = "https://api.elevenlabs.io/v1";
const OUTPUT_FORMAT = "mp3_44100_128";
const DEFAULT_VOICE_ID = "EXAVITQu4vr4xnSDxMaL";
const MUSIC_LENGTH_MS = Math.round((TOTAL_FRAMES_V2 / FPS_V2) * 1000);

async function loadLocalEnv() {
	const envPath = path.join(projectRoot, ".env.local");
	try {
		const raw = await readFile(envPath, "utf8");
		for (const line of raw.split(/\r?\n/)) {
			const trimmed = line.trim();
			if (!trimmed || trimmed.startsWith("#")) continue;
			const separator = trimmed.indexOf("=");
			if (separator === -1) continue;
			const key = trimmed.slice(0, separator).trim();
			const value = trimmed
				.slice(separator + 1)
				.trim()
				.replace(/^['"]|['"]$/g, "");
			process.env[key] ??= value;
		}
	} catch (err) {
		if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
	}
}

async function elevenLabsAudioRequest(endpoint: string, body: unknown) {
	const apiKey = process.env["ELEVENLABS_API_KEY"];
	if (!apiKey) {
		throw new Error("Missing ELEVENLABS_API_KEY. Export it or put it in apps/trailer/.env.local.");
	}
	const response = await fetch(`${API_BASE}${endpoint}`, {
		method: "POST",
		headers: {
			"Content-Type": "application/json",
			Accept: "audio/mpeg",
			"xi-api-key": apiKey,
		},
		body: JSON.stringify(body),
	});
	if (!response.ok) {
		const text = await response.text();
		throw new Error(`ElevenLabs request failed (${response.status}): ${text}`);
	}
	return Buffer.from(await response.arrayBuffer());
}

async function generateVoiceoverForBeat(key: CopyKey, text: string): Promise<boolean> {
	if (!text) return false;
	const voiceId = process.env["ELEVENLABS_VOICE_ID"] ?? DEFAULT_VOICE_ID;
	try {
		const buf = await elevenLabsAudioRequest(
			`/text-to-speech/${voiceId}?output_format=${OUTPUT_FORMAT}`,
			{
				text,
				model_id: process.env["ELEVENLABS_TTS_MODEL"] ?? "eleven_v3",
				voice_settings: {
					stability: 0.42,
					similarity_boost: 0.78,
					style: 0.32,
					use_speaker_boost: true,
				},
				apply_text_normalization: "on",
				seed: 342187,
			}
		);
		await writeFile(path.join(outputDir, `vo-${key}.mp3`), buf);
		console.log(`[audio-v2] wrote vo-${key}.mp3 (${buf.byteLength} bytes)`);
		return true;
	} catch (err) {
		console.warn(`[audio-v2] vo-${key} failed:`, (err as Error).message);
		return false;
	}
}

async function generateMusic(): Promise<boolean> {
	try {
		const music = await elevenLabsAudioRequest(`/music?output_format=${OUTPUT_FORMAT}`, {
			prompt: HERO_V2_MUSIC_PROMPT,
			music_length_ms: MUSIC_LENGTH_MS,
			model_id: "music_v1",
			force_instrumental: true,
		});
		await writeFile(path.join(outputDir, "music.mp3"), music);
		console.log("[audio-v2] wrote music.mp3");
		return true;
	} catch (err) {
		console.warn("[audio-v2] music unavailable:", (err as Error).message);
		return false;
	}
}

const MANIFEST_PATH = path.resolve(projectRoot, "src/hero/build-v2/audioManifest.gen.ts");

async function writeManifest(voiceover: Record<CopyKey, boolean>, music: boolean) {
	const lines: string[] = [];
	lines.push("// Auto-generated by scripts/generate-audio-v2.ts — do not edit manually.");
	lines.push('import type { CopyKey } from "./beat-copy";');
	lines.push("");
	lines.push("export const AUDIO_AVAILABLE_V2: {");
	lines.push("\tmusic: boolean;");
	lines.push("\tvoiceover: Record<CopyKey, boolean>;");
	lines.push(`} = {`);
	lines.push(`\tmusic: ${music},`);
	lines.push("\tvoiceover: {");
	for (const [k, v] of Object.entries(voiceover)) {
		lines.push(`\t\t${k}: ${v},`);
	}
	lines.push("\t},");
	lines.push("};");
	await writeFile(MANIFEST_PATH, lines.join("\n") + "\n");
}

async function main() {
	await loadLocalEnv();
	await mkdir(outputDir, { recursive: true });

	const voiceover: Record<string, boolean> = {};
	for (const beat of BEAT_COPY) {
		voiceover[beat.key] = await generateVoiceoverForBeat(beat.key, beat.voiceover);
	}
	const music = await generateMusic();

	await writeManifest(voiceover as Record<CopyKey, boolean>, music);
	const okCount = Object.values(voiceover).filter(Boolean).length;
	console.log(
		`[audio-v2] manifest written. music:${music} voiceover ok:${okCount}/${Object.keys(voiceover).length}`
	);
}

main().catch((err) => {
	console.error("[audio-v2] generation failed:", err);
	process.exit(1);
});
