// Auto-generated by scripts/generate-audio-v2.ts — do not edit manually.
import type { CopyKey } from "./beat-copy";

export const AUDIO_AVAILABLE_V2: {
	music: boolean;
	voiceover: Record<CopyKey, boolean>;
} = {
	music: false,
	voiceover: {
		intro: true,
		collapse: true,
		tabs: true,
		sidebar: true,
		reposCascade: true,
		worktrees: true,
		agentBadges: true,
		rightDiff: true,
		splitPane: true,
		rightChanges: true,
		review: true,
		commentsSolve: true,
		tickets: true,
		prs: true,
		reveal: true,
	},
};
