import { type LspPreset, defineServerConfig } from "../../shared/lsp-schema";

export type { LspPreset };

export const LSP_PRESETS: LspPreset[] = [
	{
		id: "csharp",
		displayName: "C#",
		description: "csharp-ls language server",
		config: defineServerConfig({
			id: "csharp",
			command: "csharp-ls",
			languages: ["csharp"],
			fileExtensions: [".cs", ".csx"],
			rootMarkers: [".sln", ".csproj", ".git"],
		}),
	},
	{
		id: "kotlin",
		displayName: "Kotlin",
		description: "Kotlin language server",
		config: defineServerConfig({
			id: "kotlin",
			command: "kotlin-language-server",
			languages: ["kotlin"],
			fileExtensions: [".kt", ".kts"],
			rootMarkers: ["build.gradle", "build.gradle.kts", ".git"],
		}),
	},
	{
		id: "swift",
		displayName: "Swift",
		description: "SourceKit-LSP",
		config: defineServerConfig({
			id: "swift",
			command: "sourcekit-lsp",
			languages: ["swift"],
			fileExtensions: [".swift"],
			rootMarkers: ["Package.swift", ".git"],
		}),
	},
	{
		id: "lua",
		displayName: "Lua",
		description: "lua-language-server",
		config: defineServerConfig({
			id: "lua",
			command: "lua-language-server",
			languages: ["lua"],
			fileExtensions: [".lua"],
			rootMarkers: [".luarc.json", ".git"],
		}),
	},
	{
		id: "zig",
		displayName: "Zig",
		description: "ZLS — Zig Language Server",
		config: defineServerConfig({
			id: "zig",
			command: "zls",
			languages: ["zig"],
			fileExtensions: [".zig"],
			rootMarkers: ["build.zig", ".git"],
		}),
	},
	{
		id: "elixir",
		displayName: "Elixir",
		description: "ElixirLS language server",
		config: defineServerConfig({
			id: "elixir",
			command: "elixir-ls",
			languages: ["elixir"],
			fileExtensions: [".ex", ".exs"],
			rootMarkers: ["mix.exs", ".git"],
		}),
	},
	{
		id: "haskell",
		displayName: "Haskell",
		description: "Haskell Language Server",
		config: defineServerConfig({
			id: "haskell",
			command: "haskell-language-server-wrapper",
			args: ["--lsp"],
			languages: ["haskell"],
			fileExtensions: [".hs"],
			rootMarkers: ["stack.yaml", "cabal.project", ".git"],
		}),
	},
	{
		id: "dart",
		displayName: "Dart",
		description: "Dart analysis server",
		config: defineServerConfig({
			id: "dart",
			command: "dart",
			args: ["language-server", "--protocol=lsp"],
			languages: ["dart"],
			fileExtensions: [".dart"],
			rootMarkers: ["pubspec.yaml", ".git"],
		}),
	},
	{
		id: "scala",
		displayName: "Scala",
		description: "Metals — Scala language server",
		config: defineServerConfig({
			id: "scala",
			command: "metals",
			languages: ["scala"],
			fileExtensions: [".scala", ".sc"],
			rootMarkers: ["build.sbt", "build.sc", ".git"],
		}),
	},
	{
		id: "ocaml",
		displayName: "OCaml",
		description: "ocamllsp language server",
		config: defineServerConfig({
			id: "ocaml",
			command: "ocamllsp",
			languages: ["ocaml"],
			fileExtensions: [".ml", ".mli"],
			rootMarkers: ["dune-project", ".git"],
		}),
	},
	{
		id: "terraform",
		displayName: "Terraform",
		description: "terraform-ls",
		config: defineServerConfig({
			id: "terraform",
			command: "terraform-ls",
			args: ["serve"],
			languages: ["terraform"],
			fileExtensions: [".tf", ".tfvars"],
			rootMarkers: [".terraform", ".git"],
		}),
	},
	{
		id: "yaml",
		displayName: "YAML",
		description: "yaml-language-server",
		config: defineServerConfig({
			id: "yaml",
			command: "yaml-language-server",
			args: ["--stdio"],
			languages: ["yaml"],
			fileExtensions: [".yaml", ".yml"],
		}),
	},
	{
		id: "bash",
		displayName: "Bash / Shell",
		description: "bash-language-server",
		config: defineServerConfig({
			id: "bash",
			command: "bash-language-server",
			args: ["start"],
			languages: ["shellscript"],
			fileExtensions: [".sh", ".bash"],
		}),
	},
	{
		id: "dockerfile",
		displayName: "Dockerfile",
		description: "docker-langserver",
		config: defineServerConfig({
			id: "dockerfile",
			command: "docker-langserver",
			args: ["--stdio"],
			languages: ["dockerfile"],
			fileNames: ["Dockerfile"],
			rootMarkers: ["Dockerfile", ".git"],
		}),
	},
	{
		id: "r",
		displayName: "R",
		description: "languageserver for R",
		config: defineServerConfig({
			id: "r",
			command: "R",
			args: ["--no-echo", "--no-save", "-e", "languageserver::run()"],
			languages: ["r"],
			fileExtensions: [".r", ".R"],
			rootMarkers: [".Rproj", ".git"],
		}),
	},
];
